# Generated by Django 3.0.8 on 2021-03-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210117_2024'),
        ('login', '0002_auto_20210315_2136'),
    ]

    operations = [
    ]
