# Generated by Django 3.0.8 on 2021-03-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_merge_20210319_2353'),
        ('login', '0003_merge_20210319_2249'),
    ]

    operations = [
    ]
